### ISSUE TITLE
select pictograms

### ISSUE THREAD

**Issue by derikon** [TactileVision/TactJam-TEI2021#5]
We need to collect and select (visual) pictograms which participants should recreate in a tactile manner.

**Comment by freitaggeorg** [comment]
Selection of four to five categories with three pictograms each. Participants are divided as groups per category and can choose pictograms. This is to prevent the participants from not finding access to the topic but also not being overwhelmed by the selection.

**Comment by derikon** [comment]
- [ ] Category (A)
  - [ ] pictogram (1)
  - [ ] pictogram (2)
  - [ ] pictogram (3)
- [ ] Category (B)
  - [ ] pictogram (1)
  - [ ] pictogram (2)
  - [ ] pictogram (3)
- [ ] Category (C)
  - [ ] pictogram (1)
  - [ ] pictogram (2)
  - [ ] pictogram (3)
- [ ] Category (D)
  - [ ] pictogram (1)
  - [ ] pictogram (2)
  - [ ] pictogram (3)

**Comment by freitaggeorg** [comment]
traffic --> stop, speed limit, right of way
hazard note --> explosiv, x-ray, easily flammable
tourism --> place of interest, viewpoint, information
corona  --> keep distance, wash your handes, wear a face mask
computer --> incoming message, low energy, connected
car --> close seat belt, glaze ice, traffic jam
